### ISSUE TITLE
Remember the size of the edit box when swiching back from Preview

### ISSUE THREAD

**Issue by ReneSac** [nim-lang/nimforum#197] opened 2018-08-11 01:42 UTC
When switching back and forth between the preview and the editing views, the forum won't remember the size of the editing box, that unlike github doesn't resize automatically with the text size either. It remains in it's default too small size and makes much slower to iterate fixing the RST when the message is more than a few lines long.

Split from #195.

**Comment by dom96** [comment] 2018-08-11 12:36
Duplicate of https://github.com/nim-lang/nimforum/issues/147

**Closed by dom96** 2018-08-11 12:36 UTC
