### ISSUE TITLE
Quote is not working properly in preview mode

### ISSUE THREAD

**Issue by cheatfate** [nim-lang/nimforum#115] opened 2018-01-15 10:58 UTC
This text
```
@2vg, please prove your words with benchmarks, or stop saying non-sense like this.

> "Or, if you do not support Windows, libev will be slightly faster than Selectors. Here is the wrapper for libev."
```
is not shows `quoted` text in preview mode.

**Comment by dom96** [comment] 2018-01-15 11:18
Yeah, there is a bug that means you need something below a quote for it to show up.

**Comment by dom96** [comment] 2018-05-19 23:12
Duplicate of #78.

**Closed by dom96** 2018-05-19 23:12 UTC
