### ISSUE TITLE
Release and Deploy

### ISSUE THREAD

**Issue by jyapayne** [nim-lang/nimforum#230] opened 2020-03-03 16:11 UTC
@dom96 or @Araq, what was the process to release and deploy a new version of the nimforum to https://forum.nim-lang.org? I'd like to see the current categories work be utilized on the website and get some user feedback

**Comment by Araq** [comment] 2020-03-03 21:38
It's a manual deploy done by @dom96 when he'll find the time.

**Comment by dom96** [comment] 2020-03-04 10:01
Yeah, I'll try to do this tomorrow or on Friday.

**Comment by jyapayne** [comment] 2020-03-08 00:18
@dom96 still planning on releasing this weekend?

**Comment by dom96** [comment] 2020-03-08 10:30
yeah, will try to deploy today.

**Comment by dom96** [comment] 2020-03-08 23:33
Looks like it'll have to wait another day, sorry!

**Comment by jyapayne** [comment] 2020-03-09 00:56
Alright. If there's anything I can do to make it easier to deploy, let me know!

**Comment by dom96** [comment] 2020-03-17 23:38
Sorry this is taking so long. I managed to build it and test it on our prod database over the weekend. A few things that need to be fixed before deployment:

* Opening a category with 5k threads breaks the forum, guess there is a very slow SQL query? Maybe with no pagination?
* User avatars are no longer left-aligned, but instead centered.
* "Default" category renamed to "Unsorted" and default colour made grey.

Most of these are minor, I will try to resolve them soon, but if you have some bandwidth I'd love the help :)

**Comment by jyapayne** [comment] 2020-03-18 01:43
Awesome, thanks for looking at it!

1. I'll take a look at the slow queries. Do you have a stress test that you usually run that generates a large amount of data?
2. The user avatars being centered was a mistake in the mobile styling fix I made. I thought that discourse did that, but I was mistaken. The left align, but they also don't have a column header for the users, which I think looks better. I can left align and remove the users header if that's good with you.
3. If you want to do this in the nim forum, the entry will already be in the DB. I can modify it in the code, but you'll have to alter the entry in the DB.

**Comment by dom96** [comment] 2020-03-18 09:29
> Do you have a stress test that you usually run that generates a large amount of data?

Sadly no, I just use our forum's DB which has 5000+ threads.

> I can left align and remove the users header if that's good with you.

I do like the users header, would prefer it be kept. I think it's up to the forum CSS to hide it.

> I can modify it in the code, but you'll have to alter the entry in the DB.

I haven't modified the master DB (I copied it onto my PC) so modifying it in the code is what I want :)

**Comment by jyapayne** [comment] 2020-03-18 12:50
> Sadly no, I just use our forum's DB which has 5000+ threads. Maybe you can create a quick script which generates this?

Yep, I'll do that. Just thought maybe you already had one. 

> I do like the users header, would prefer it be kept. I think it's up to the forum CSS to hide it.

Fair enough, I'll keep it in :)

> I haven't modified the master DB (I copied it onto my PC) so modifying it in the code is what I want :)

👍

**Comment by jyapayne** [comment] 2020-03-18 14:14
Hmm, I can't reproduce your error with 5k threads. I generated 100k threads under the default category and it loads perfectly fine. Pagination is there and working. What was the error you were seeing?

**Comment by jyapayne** [comment] 2020-03-18 14:16
PR is here for the other issues: https://github.com/nim-lang/nimforum/pull/236

**Comment by jyapayne** [comment] 2020-03-22 23:14
@dom96 can you give more details on the error encountered at 5000 threads? Like I said, I created a script that has 100k threads with no issue. Maybe it's a different issue?

**Comment by dom96** [comment] 2020-03-26 22:58
> @dom96 can you give more details on the error encountered at 5000 threads? Like I said, I created a script that has 100k threads with no issue. Maybe it's a different issue?

The forum just stops responding to any requests. I will try to look into it this weekend.

**Comment by jyapayne** [comment] 2020-04-26 16:49
@dom96 any update on this?

**Comment by dom96** [comment] 2020-04-28 20:09
Sorry, no, busy with other projects right now.

**Comment by jyapayne** [comment] 2020-05-10 12:44
@dom96 then would it be possible for you to give someone else the authority to deploy? It's unfair to make us wait when there are lots of other devs who could do the deploy and debug the issues. I would be happy to do it, but if that doesn't work for you, anyone else on the Nim team would work.

**Comment by dom96** [comment] 2020-05-10 14:41
@Araq @narimiran can either of you help with this?

**Comment by jyapayne** [comment] 2020-07-24 22:04
Anyone?

**Comment by dom96** [comment] 2020-07-25 00:07
@narimiran was looking into this. I've pinged him again to see whether there was any progress.

**Comment by narimiran** [comment] 2020-07-25 19:03
> I've pinged him again to see whether there was any progress.

No progress since the last time we spoke.

IIRC, I was able to run the updated forum on my machine, but some features didn't work. I haven't looked more closely into it after that.

**Comment by narimiran** [comment] 2020-08-06 08:23
@dom96 @jyapayne I've pulled the latest commits, fixed one long-deprecated (now gone) import, then I've rebuilt frontend (`nimble frontend`), and ran the forum, and: it seems to be running now!

![screenshot](https://imgur.com/jQkEUwn.jpg)

There is only one category: `Default`, and I'm not sure how can I (as a moderator) create new categories and move some posts to that category?

**Comment by jyapayne** [comment] 2020-08-06 12:00
Wonderful! To add categories, click the "Categories" button at the top, then on the next page, you should see a Categories drop down with a plus button beside it. Clicking that will let you add categories.

There's no easy way to assign many posts a category. Right now, you have to do it one by one by clicking into the post, and selecting the category from the drop down.

**Comment by narimiran** [comment] 2020-08-06 12:06
> To add categories, click the "Categories" button at the top, then on the next page, you should see a Categories drop down with a plus button beside it. Clicking that will let you add categories.

This is how it looks for me after I click "Categories" button:

![img](https://imgur.com/nqKBzID.jpg)

Are you sure that this option is available to *moderators*, not just *admins*?

**Comment by jyapayne** [comment] 2020-08-06 12:14
Ah yes, I forgot because it's been a while. I did only make the option available to admins but I'm not sure what the reasoning was. @dom96 is there a reason moderators should not have the capability to add categories?

**Comment by narimiran** [comment] 2020-08-06 12:40
> @dom96 is there a reason moderators should not have the capability to add categories?

IMO no. More manpower is better.

I've made a PR to enable this: https://github.com/nim-lang/nimforum/pull/255

**Comment by dom96** [comment] 2020-08-06 15:21
@narimiran did you click on the "Default" category? IIRC that was when things started being unstable.

**Comment by dom96** [comment] 2020-08-06 15:30
The reason I think only admins should be able to add/remove categories is because I don't want the number of categories to devolve into a massive number of inconsistencies (like we have with the GitHub issue labels). If we want to change the categories that are available we should discuss it, and at that point the admins can easily take care of that.

**Comment by narimiran** [comment] 2020-08-06 19:50
> @narimiran did you click on the "Default" category? IIRC that was when things started being unstable.

Yes, it worked fine.

As I said earlier:

> I would propose that @dom96 should run it on his own machine to double-check that now everything is indeed working as intended.

**Comment by narimiran** [comment] 2020-08-24 11:47
Ping @dom96!

**Comment by dom96** [comment] 2020-08-24 19:13
Just tested it again, as soon as I navigate to the default category the forum hangs:

![image](https://user-images.githubusercontent.com/246651/91086003-2c169c80-e646-11ea-851b-a5e43260daf3.png)

I can see in the terminal that it's stuck trying to retrieve all the threads: 
![image](https://user-images.githubusercontent.com/246651/91086038-3afd4f00-e646-11ea-8d63-829125702e8b.png)

And when I kill it, the stack trace shows it's blocked on `getAllRows`.

**Comment by dom96** [comment] 2020-08-24 20:46
That took far longer than it should have, but it is now deployed. The deployment was much easier than I thought it'd be, so I think I can commit to doing this far more often. The performance regression was definitely there though and I had to spend some time fixing it. But anyway... enjoy :)

https://forum.nim-lang.org/t/6725

**Closed by dom96** 2020-08-24 20:46 UTC

**Comment by jyapayne** [comment] 2020-08-24 21:01
Cool! That's awesome news!

I took a look at the forum. Did you disable categories? I don't seem to see any at the moment

**Comment by dom96** [comment] 2020-08-24 21:32
Caching is a bitch, you just gotta hard refresh :)
